# Naive Bayes Using Gaussian

In [8]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

X, y = datasets.load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40, stratify=y)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [9]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

predGnb = gnb.predict(X_test)
print(accuracy_score(y_test, predGnb))
print(confusion_matrix(y_test, predGnb))

0.9333333333333333
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
