# Naive Bayes Using K-Nearest Neighbor

In [19]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [20]:
X, y = datasets.load_iris(return_X_y = True)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50, stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [22]:
knn = KNeighborsClassifier(n_neighbors=11, weights='distance')
knn.fit(X_train, y_train)

predKnn = knn.predict(X_test)
print(accuracy_score(y_test, predKnn))
print(confusion_matrix(y_test, predKnn))

0.9666666666666667
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
